const SOCKET_TYPES = {
	CONVERSATION_LIST_EVENT: 'conversation_list',
	CLEAR_PENDING_EVENT: 'clear_pending',
	PREVIOUS_MESSAGES_EVENT: 'previous_messages',
	MULTIPLE_PREVIOUS_MESSAGES_EVENT: 'multiple_previous_messages',
	SEND_MESSAGE_EVENT: 'send_message',
	SEND_MESSAGE_TO_NEW_USER_EVENT: 'SEND_MESSAGE_TO_NEW_USER_EVENT',
	RECEIVE_MESSAGE_EVENT: 'receive_message',
	SEARCH_PERSON_EVENT: 'SEARCH_PERSON_EVENT',
	GET_USER_INFO_EVENT: 'GET_USER_INFO_EVENT',
	ERROR: 'ERROR',
};

const ERROR_TYPES = {
	WRITER_RESTRICTION_ERROR: 'WRITER_RESTRICTION_ERROR',
};

module.exports = { SOCKET_TYPES, ERROR_TYPES };
